"""Curated Mechabellum unit definitions and matchup ratings."""

UNIT_IMAGES = {
    "Crawler":       "crawler.jpg",
    "Fang":          "fang.jpg",
    "Hound":         "hound.jpg",
    "Void Eye":      "void_eye.jpg",
    "Marksman":      "marksman.jpg",
    "Arclight":      "arclight.jpg",
    "Wasp":          "wasp.jpg",
    "Mustang":       "mustang.jpg",
    "Sledgehammer":  "sledgehammer.jpg",
    "Steelballs":    "steelball.jpg",
    "Stormcaller":   "stormcaller.jpg",
    "Phoenix":       "phoenix.jpg",
    "Phantom Ray":   "phantom_ray.jpg",
    "Tarantula":     "tarantula.jpg",
    "Sabertooth":    "sabertooth.jpg",
    "Rhino":         "rhino.jpg",
    "Hacker":        "hacker.jpg",
    "Wraith":        "wraith.jpg",
    "Scorpion":      "scorpion.jpg",
    "Vulcan":        "vulcan.jpg",
    "Fortress":      "fortress.jpg",
    "Melting Point": "melting_point.jpg",
    "Sandworm":      "sandworm.jpg",
    "Raiden":        "raiden.jpg",
    "Overlord":      "overlord.jpg",
    "War Factory":   "war_factory.jpg",
    "Abyss":         "abyss.jpg",
    "Mountain":      "mountain.jpg",
    "Fire Badger":   "fire_badger.jpg",
    "Typhoon":       "typhoon.jpg",
    "Farseer":       "farseer.jpg",
}

S, A, B, C, D, E = 5, 4, 3, 2, 1, 0

UNIT_MATRIX = {
    "Crawler":       [C, B, D, A, A, E, E, E, A, D, A, E, A, E, E, D, B, D, A, E, D, C, D, E, E, A, A, D, E, E, D, E, D],
    "Fang":          [D, C, D, C, A, E, E, B, D, D, C, E, E, A, B, D, D, D, A, E, D, D, E, E, E, C, B, D, B, B, D, D, D],
    "Hound":         [A, A, C, D, D, E, D, E, C, D, D, D, B, E, E, D, C, D, D, E, D, D, D, E, D, D, C, D, E, E, D, E, D],
    "Void Eye":      [D, D, A, C, D, E, D, E, C, B, D, A, B, E, E, B, C, C, A, E, C, C, C, E, D, D, B, D, E, E, D, E, D],
    "Marksman":      [D, D, B, B, C, E, S, D, D, D, D, A, D, S, D, B, D, D, S, A, D, C, C, E, B, D, D, D, D, A, D, D, D],
    "Vortex":        [C, A, A, D, C, E, A, A, B, B, D, B, D, C, C, D, D, D, B, A, C, D, C, E, B, D, D, D, D, D, D, C, D],
    "Arclight":      [S, S, B, C, E, E, C, E, A, D, D, D, E, E, E, D, D, D, D, E, D, E, D, E, D, E, E, D, E, E, E, E, D],
    "Wasp":          [S, D, S, D, C, E, S, C, D, S, S, S, S, B, D, S, S, A, S, E, D, S, D, E, S, S, B, S, B, B, A, D, A],
    "Mustang":       [D, B, D, D, B, E, D, B, C, E, E, D, D, A, C, D, D, D, B, D, D, D, D, E, E, D, D, D, B, B, D, D, B],
    "Sledgehammer":  [A, A, B, D, C, E, A, E, S, C, D, D, B, E, E, D, D, D, B, E, D, E, B, E, D, E, D, D, E, E, E, E, D],
    "Steelballs":    [D, D, B, B, B, E, A, E, A, B, C, B, A, E, E, B, C, A, E, E, C, D, A, E, B, C, B, D, E, E, D, E, B],
    "Fire Badger":   [S, S, B, D, D, E, B, E, A, C, D, C, A, E, E, D, D, D, D, E, D, E, B, E, D, E, D, D, E, E, E, E, E],
    "Stormcaller":   [D, S, D, D, B, E, S, E, C, D, D, D, C, E, E, B, B, E, S, E, D, S, A, E, A, B, A, E, E, E, D, E, C],
    "Phoenix":       [S, E, S, S, D, E, S, D, D, S, A, S, S, C, D, S, S, S, S, A, D, S, B, E, S, S, D, S, D, B, A, D, S],
    "Phantom Ray":   [A, D, S, S, C, E, S, C, D, S, S, S, S, C, C, S, S, S, S, A, D, S, B, E, S, S, D, S, D, C, A, D, S],
    "Tarantula":     [A, A, B, D, D, E, B, E, B, B, D, B, D, E, E, C, D, D, C, E, C, D, A, E, B, D, D, D, E, E, D, E, D],
    "Sabertooth":    [D, C, D, D, C, E, A, E, B, B, D, A, D, E, E, A, C, B, A, E, A, B, A, E, A, D, D, D, E, E, D, E, D],
    "Rhino":         [C, C, B, D, C, E, A, E, B, B, D, A, S, E, E, B, D, C, A, E, A, A, A, E, A, D, E, D, E, E, E, E, D],
    "Hacker":        [D, E, C, D, E, E, B, E, D, D, S, A, E, E, E, D, D, D, C, E, D, D, A, E, D, E, D, D, E, E, E, E, D],
    "Wraith":        [S, B, S, S, D, E, S, S, B, S, A, S, S, D, D, A, A, A, S, C, D, A, D, E, A, A, E, A, D, D, A, D, A],
    "Farseer":       [C, A, A, D, C, E, A, A, B, B, D, B, D, C, C, D, D, D, B, A, C, D, C, E, B, D, D, D, D, D, D, C, D],
    "Scorpion":      [D, A, A, D, D, E, A, E, A, A, S, S, D, E, E, B, D, D, A, E, B, C, S, E, S, D, D, D, E, E, D, E, D],
    "Typhoon":       [A, S, B, D, D, E, C, S, B, D, D, D, D, D, D, B, D, E, D, C, D, E, C, E, D, D, D, D, D, D, D, D, C],
    "Centurion":     [C, A, A, D, C, E, A, A, B, B, D, B, D, C, C, D, D, D, B, A, C, D, C, E, B, D, D, D, D, D, D, C, D],
    "Vulcan":        [S, S, A, B, D, E, B, E, S, B, D, A, D, E, E, D, D, D, C, E, D, D, B, E, C, D, D, D, E, E, D, E, D],
    "Fortress":      [D, D, C, C, B, E, S, E, C, A, D, S, D, E, E, A, C, A, S, E, A, B, A, E, A, C, E, D, E, E, D, E, D],
    "Melting Point": [D, D, D, D, C, E, A, D, C, B, D, A, D, B, B, A, B, S, S, S, A, A, A, E, S, S, C, B, A, B, B, B, B],
    "Sandworm":      [B, B, B, B, S, E, S, E, B, A, D, S, S, E, E, B, B, C, A, E, A, B, A, E, A, C, D, C, E, E, D, E, D],
    "Raiden":        [S, D, S, S, C, E, S, D, D, S, S, S, S, A, A, S, S, S, S, S, B, S, A, E, S, S, D, B, C, D, S, D, A],
    "Overlord":      [S, D, S, S, D, E, S, D, D, S, S, S, S, D, D, S, S, S, S, S, A, S, A, E, S, S, D, S, B, C, S, D, S],
    "War Factory":   [B, A, A, B, A, E, S, E, A, S, A, S, B, E, E, S, A, A, D, E, A, A, A, E, S, B, D, A, E, E, C, E, D],
    "Abyss":         [S, A, S, S, B, E, S, B, C, S, S, S, S, A, B, S, S, S, S, S, D, S, A, E, S, S, D, A, A, B, S, C, S],
    "Mountain":      [C, A, A, B, B, E, S, E, B, A, D, S, D, E, E, A, B, B, D, E, C, B, A, E, A, B, D, B, E, E, B, D, C],
}

UNIT_OVERRIDES = {
    "Crawler: Acid": {"War Factory": B, "Sandworm": B, "Mountain": B},
    "Fang: Rage": {"Stormcaller": C},
    "Fang: Ignite": {"Fortress": A, "Melting Point": A, "Sandworm": B, "Raiden": A, "Overlord": A, "War Factory": A, "Mountain": B},
    "Void Eye: Aerial Mode": {"Wasp": A, "Phoenix": B, "Phantom Ray": C, "Wraith": A, "Raiden": C, "Overlord": B},
    "Marksman: Aerial Specialization": {"Raiden": S},
    "Arclight: Anti-Aircraft Ammunition": {"Wasp": S, "Wraith": D},
    "Arclight: Charged Shot": {"Sledgehammer": B, "Steelballs": A, "Rhino": C, "Vulcan": B},
    "Wasp: Aerial Specialization": {"Wraith": C, "Overlord": A},
    "Mustang: Aerial Specialization": {"Phantom Ray": B, "Wraith": B, "Overlord": A, "Abyss": B},
    "Mustang: Missile Interception": {"Stormcaller": B, "Phantom Ray": A, "Farseer": A},
    "Mustang: Range Enhancement": {"Farseer": A}, "Mustang: Map Position": {"Stormcaller": D, "Abyss": D},
    "Sledgehammer: Armor-Piercing Bullets": {"Rhino": B}, "Sledgehammer: Range Enhancement": {"Vulcan": C},
    "Sledgehammer: Armor Enhancement": {"Tarantula": C, "Vulcan": C, "Fire Badger": S},
    "Steelballs: Range Enhancement": {"Hacker": B, "War Factory": C}, "Steelballs: Armor Enhancement": {"Crawler": B, "Fang": A},
    "Steelballs: Mechanical Division": {"Scorpion": B}, "Steelballs: Map Position": {"Marksman": C},
    "Stormcaller: Map Position": {"Mustang": D, "Farseer": B}, "Phoenix: Range Enhancement": {"Farseer": C},
    "Phoenix: Map Position": {"Overlord": C}, "Phantom Ray: Armor Enhancement": {"Fang": S, "Mustang": A},
    "Tarantula: Anti-Aircraft Ammunition": {"Wasp": A, "Phoenix": D, "Phantom Ray": C, "Wraith": A},
    "Sabertooth: Secondary Armament": {"Hound": A, "Void Eye": B}, "Sabertooth: Double Shot": {"Fortress": B, "Melting Point": A, "Sandworm": B},
    "Rhino: Whirlwind": {"Steelballs": B}, "Rhino: Final Blitz": {"Steelballs": B}, "Rhino: Unit Cover": {"Hacker": A},
    "Hacker: Range Enhancement": {"Tarantula": C, "Vulcan": A}, "Hacker: Unit Cover": {"Rhino": A},
    "Wraith: Armor + Field Maintenance": {"Typhoon": A}, "Scorpion: Range + Siege Mode": {"Stormcaller": A},
    "Scorpion: Double Shot + Range + Siege Mode + Acid": {"Fortress": B, "Melting Point": B}, "Scorpion: Acid": {"Mountain": C},
    "Fortress: Rocket Punch": {"Crawler": C, "Fang": B, "Steelballs": B, "Stormcaller": B, "Sandworm": C}, "Fortress: Anti-Air": {"Wasp": B},
    "Fortress: Fang Production": {"Steelballs": A, "Sandworm": C},
    "Melting Point: Energy Diffraction": {"Fang": B, "Void Eye": C, "Wasp": B, "Mustang": B, "Sledgehammer": A},
    "Sandworm: Anti-Aerial": {"Wasp": B, "Phoenix": A, "Phantom Ray": C, "Wraith": A, "Raiden": A, "Overlord": C},
    "Overlord: Mothership": {"Phoenix": A}, "Overlord: Armor Enhancement": {"Fang": S, "Mustang": A},
    "Abyss: Map Position": {"Phoenix": B},
    "Mountain: Anti-Aircraft Ammunition": {"Wasp": B, "Phoenix": B, "Phantom Ray": B, "Wraith": A, "Raiden": A, "Overlord": A},
    "Typhoon: Aerial Specialization": {"Phantom Ray": A, "Overlord": C},
    "Farseer: Missile": {"Stormcaller": B, "Phantom Ray": A, "Overlord": B}, "Farseer: Map Position": {"Stormcaller": C},
}

UNITS = list(UNIT_MATRIX)
UNITS_TECH = list(UNIT_OVERRIDES)
RATING_DETAILS = {
    S: ("S", "Wins with more than 95% health remaining and almost no damage taken."),
    A: ("A", "Wins with roughly 60–95% health remaining."),
    B: ("B", "Wins with roughly 10–60% health remaining."),
    C: ("C", "Wins with less than 10% health remaining."),
    D: ("D", "Loses, but damages the opponent."),
    E: ("E", "Loses while the opponent retains more than 95% health."),
}
