"""Curated Mechabellum unit definitions and matchup ratings."""

UNIT_IMAGES = {
    "Crawler": "crawler.jpg", "Fang": "fang.jpg", "Hound": "hound.jpg",
    "Void Eye": "void_eye.jpg", "Marksman": "marksman.jpg", "Arclight": "arclight.jpg",
    "Wasp": "wasp.jpg", "Mustang": "mustang.jpg", "Sledgehammer": "sledgehammer.jpg",
    "Steelballs": "steelball.jpg", "Stormcaller": "stormcaller.jpg", "Phoenix": "phoenix.jpg",
    "Phantom Ray": "phantom_ray.jpg", "Tarantula": "tarantula.jpg", "Sabertooth": "sabertooth.jpg",
    "Rhino": "rhino.jpg", "Hacker": "hacker.jpg", "Wraith": "wraith.jpg",
    "Scorpion": "scorpion.jpg", "Vulcan": "vulcan.jpg", "Fortress": "fortress.jpg",
    "Melting Point": "melting_point.jpg", "Sandworm": "sandworm.jpg", "Raiden": "raiden.jpg",
    "Overlord": "overlord.jpg", "War Factory": "war_factory.jpg", "Abyss": "abyss.jpg",
    "Mountain": "mountain.jpg", "Fire Badger": "fire_badger.jpg", "Typhoon": "typhoon.jpg",
    "Farseer": "farseer.jpg",
}

S, A, B, C, D, E = 5, 4, 3, 2, 1, 0

UNIT_MATRIX = {
    "Crawler": [C, B, D, A, A, E, E, A, D, A, A, E, E, D, B, D, A, E, C, E, A, A, D, E, E, D, E, D, E, D, D],
    "Fang": [D, C, D, C, A, E, B, D, D, C, E, A, B, D, D, D, A, E, D, E, C, B, D, B, B, D, D, D, E, E, D],
    "Hound": [A, A, C, D, D, D, E, C, D, D, B, E, E, D, C, D, D, E, D, D, D, C, D, E, E, D, E, D, D, D, D],
    "Void Eye": [D, D, A, C, D, D, E, C, B, D, B, E, E, B, C, C, A, E, C, D, D, B, D, E, E, D, E, D, A, C, C],
    "Marksman": [D, D, B, B, C, S, D, D, D, D, D, S, D, B, D, D, S, A, C, B, D, D, D, D, A, D, D, D, A, C, D],
    "Arclight": [S, S, B, C, E, C, E, A, D, D, E, E, E, D, D, D, D, E, E, D, E, E, D, E, E, E, E, D, D, D, D],
    "Wasp": [S, D, S, D, C, S, C, D, S, S, S, B, D, S, S, A, S, E, S, S, S, B, S, B, B, A, D, A, S, D, D],
    "Mustang": [D, B, D, D, B, D, B, C, E, E, D, A, C, D, D, D, B, D, D, E, D, D, D, B, B, D, D, B, D, D, D],
    "Sledgehammer": [A, A, B, D, C, A, E, S, C, D, B, E, E, D, D, D, B, E, E, D, E, D, D, E, E, E, E, D, D, B, D],
    "Steelballs": [D, D, B, B, B, A, E, A, B, C, A, E, E, B, C, A, E, E, D, B, C, B, D, E, E, D, E, B, B, A, C],
    "Stormcaller": [D, S, D, D, B, S, E, C, D, D, C, E, E, B, B, E, S, E, S, A, B, A, E, E, E, D, E, C, D, A, D],
    "Phoenix": [S, E, S, S, D, S, D, D, S, A, S, C, D, S, S, S, S, A, S, S, S, D, S, D, B, A, D, S, S, B, D],
    "Phantom Ray": [A, D, S, S, C, S, C, D, S, S, S, C, C, S, S, S, S, A, S, S, S, D, S, D, C, A, D, S, S, B, D],
    "Tarantula": [A, A, B, D, D, B, E, B, B, D, D, E, E, C, D, D, C, E, D, B, D, D, D, E, E, D, E, D, B, A, C],
    "Sabertooth": [D, C, D, D, C, A, E, B, B, D, D, E, E, A, C, B, A, E, B, A, D, D, D, E, E, D, E, D, A, A, A],
    "Rhino": [C, C, B, D, C, A, E, B, B, D, S, E, E, B, D, C, A, E, A, A, D, E, D, E, E, E, E, D, A, A, A],
    "Hacker": [D, E, C, D, E, B, E, D, D, S, E, E, E, D, D, D, C, E, D, D, E, D, D, E, E, E, E, D, A, A, D],
    "Wraith": [S, B, S, S, D, S, S, B, S, A, S, D, D, A, A, A, S, C, A, A, A, E, A, D, D, A, D, A, S, D, D],
    "Scorpion": [D, A, A, D, D, A, E, A, A, S, D, E, E, B, D, D, A, E, C, S, D, D, D, E, E, D, E, D, S, S, B],
    "Vulcan": [S, S, A, B, D, B, E, S, B, D, D, E, E, D, D, D, C, E, D, C, D, D, D, E, E, D, E, D, A, B, D],
    "Fortress": [D, D, C, C, B, S, E, C, A, D, D, E, E, A, C, A, S, E, B, A, C, E, D, E, E, D, E, D, S, A, A],
    "Melting Point": [D, D, D, D, C, A, D, C, B, D, D, B, B, A, B, S, S, S, A, S, S, C, B, A, B, B, B, B, A, A, A],
    "Sandworm": [B, B, B, B, S, S, E, B, A, D, S, E, E, B, B, C, A, E, B, A, C, D, C, E, E, D, E, D, S, A, A],
    "Raiden": [S, D, S, S, C, S, D, D, S, S, S, A, A, S, S, S, S, S, S, S, S, D, B, C, D, S, D, A, S, A, B],
    "Overlord": [S, D, S, S, D, S, D, D, S, S, S, D, D, S, S, S, S, S, S, S, S, D, S, B, C, S, D, S, S, A, A],
    "War Factory": [B, A, A, B, A, S, E, A, S, A, B, E, E, S, A, A, D, E, A, S, B, D, A, E, E, C, E, D, S, A, A],
    "Abyss": [S, A, S, S, B, S, B, C, S, S, S, A, B, S, S, S, S, S, S, S, S, D, A, A, B, S, C, S, S, A, D],
    "Mountain": [C, A, A, B, B, S, E, B, A, D, D, E, E, A, B, B, D, E, B, A, B, D, B, E, E, B, D, C, S, A, C],
    "Fire Badger": [S, S, B, D, D, B, E, A, C, D, A, E, E, D, D, D, D, E, E, D, E, D, D, E, E, E, E, E, C, B, D],
    "Typhoon": [A, S, B, D, D, C, S, B, D, D, D, D, D, B, D, E, D, C, E, D, D, D, D, D, D, D, D, C, D, C, D],
    "Farseer": [C, A, A, D, C, A, A, B, B, D, D, C, C, D, D, D, B, A, D, B, D, D, D, D, D, D, C, D, B, C, C],
}

UNIT_OVERRIDES = {
    "Crawler: Acid": {"War Factory": B, "Sandworm": B, "Mountain": B},
    "Fang: Rage": {"Stormcaller": C},
    "Fang: Ignite": {"Fortress": A, "Melting Point": A, "Sandworm": B, "Raiden": A, "Overlord": A, "War Factory": A, "Mountain": B},
    "Void Eye: Aerial Mode": {"Wasp": A, "Phoenix": B, "Phantom Ray": C, "Wraith": A, "Raiden": C, "Overlord": B},
    "Marksman: Aerial Specialization": {"Raiden": S},
    "Arclight: Anti-Aircraft Ammunition": {"Wasp": S, "Wraith": D},
    "Arclight: Charged Shot": {"Sledgehammer": B, "Steelballs": A, "Rhino": C, "Vulcan": B},
    "Wasp: Aerial Specialization": {"Wraith": C, "Overlord": A},
    "Mustang: Aerial Specialization": {"Phantom Ray": B, "Wraith": B, "Overlord": A, "Abyss": B},
    "Mustang: Missile Interception": {"Stormcaller": B, "Phantom Ray": A, "Farseer": A},
    "Mustang: Range Enhancement": {"Farseer": A}, "Mustang: Map Position": {"Stormcaller": D, "Abyss": D},
    "Sledgehammer: Armor-Piercing Bullets": {"Rhino": B}, "Sledgehammer: Range Enhancement": {"Vulcan": C},
    "Sledgehammer: Armor Enhancement": {"Tarantula": C, "Vulcan": C, "Fire Badger": S},
    "Steelballs: Range Enhancement": {"Hacker": B, "War Factory": C}, "Steelballs: Armor Enhancement": {"Crawler": B, "Fang": A},
    "Steelballs: Mechanical Division": {"Scorpion": B}, "Steelballs: Map Position": {"Marksman": C},
    "Stormcaller: Map Position": {"Mustang": D, "Farseer": B}, "Phoenix: Range Enhancement": {"Farseer": C},
    "Phoenix: Map Position": {"Overlord": C}, "Phantom Ray: Armor Enhancement": {"Fang": S, "Mustang": A},
    "Tarantula: Anti-Aircraft Ammunition": {"Wasp": A, "Phoenix": D, "Phantom Ray": C, "Wraith": A},
    "Sabertooth: Secondary Armament": {"Hound": A, "Void Eye": B}, "Sabertooth: Double Shot": {"Fortress": B, "Melting Point": A, "Sandworm": B},
    "Rhino: Whirlwind": {"Steelballs": B}, "Rhino: Final Blitz": {"Steelballs": B}, "Rhino: Unit Cover": {"Hacker": A},
    "Hacker: Range Enhancement": {"Tarantula": C, "Vulcan": A}, "Hacker: Unit Cover": {"Rhino": A},
    "Wraith: Armor + Field Maintenance": {"Typhoon": A}, "Scorpion: Range + Siege Mode": {"Stormcaller": A},
    "Scorpion: Double Shot + Range + Siege Mode + Acid": {"Fortress": B, "Melting Point": B}, "Scorpion: Acid": {"Mountain": C},
    "Fortress: Rocket Punch": {"Crawler": C, "Fang": B, "Steelballs": B, "Stormcaller": B, "Sandworm": C}, "Fortress: Anti-Air": {"Wasp": B},
    "Fortress: Fang Production": {"Steelballs": A, "Sandworm": C},
    "Melting Point: Energy Diffraction": {"Fang": B, "Void Eye": C, "Wasp": B, "Mustang": B, "Sledgehammer": A},
    "Sandworm: Anti-Aerial": {"Wasp": B, "Phoenix": A, "Phantom Ray": C, "Wraith": A, "Raiden": A, "Overlord": C},
    "Overlord: Mothership": {"Phoenix": A}, "Overlord: Armor Enhancement": {"Fang": S, "Mustang": A},
    "Abyss: Map Position": {"Phoenix": B},
    "Mountain: Anti-Aircraft Ammunition": {"Wasp": B, "Phoenix": B, "Phantom Ray": B, "Wraith": A, "Raiden": A, "Overlord": A},
    "Typhoon: Aerial Specialization": {"Phantom Ray": A, "Overlord": C},
    "Farseer: Missile": {"Stormcaller": B, "Phantom Ray": A, "Overlord": B}, "Farseer: Map Position": {"Stormcaller": C},
}

UNITS = list(UNIT_MATRIX)
UNITS_TECH = list(UNIT_OVERRIDES)
RATING_DETAILS = {
    S: ("S", "Wins with more than 95% health remaining and almost no damage taken."),
    A: ("A", "Wins with roughly 60–95% health remaining."),
    B: ("B", "Wins with roughly 10–60% health remaining."),
    C: ("C", "Wins with less than 10% health remaining."),
    D: ("D", "Loses, but damages the opponent."),
    E: ("E", "Loses while the opponent retains more than 95% health."),
}
